title: Rakesh Emuru
logo:  "https://github.com/rakesh-emuru/rakesh-emuru.github.io/blob/main/Images/rakesh_emuru.jpg?raw=true"
description: >
  I am Rakesh Emuru, a Master's candidate at the <strong>University of Delaware</strong> with a specialization in <strong>Data Science</strong>. I possess a strong background in harnessing machine learning models, complemented by full-stack development expertise gained during my time at Trendlyne. I have successfully automated and optimized data solutions that serve millions. I'm actively seeking Data Science internships to further refine and utilize my Data Science skills.
  <br><br>
  <a href="https://www.linkedin.com/in/rakesh-emuru/" title="Connect with Rakesh Emuru on LinkedIn">Connect on LinkedIn</a> <br><br>
  <a href="https://drive.google.com/file/d/1k1OtrgLC2-NVoZrlW3ribeHk6oGGRSyb/view?usp=sharing" title="View Rakesh Emuru's Resume">View My Resume</a><br><br>
  <a href="mailto:emururakesh@gmail.com" title="Send an email to Rakesh Emuru">Send me an email!</a>

theme: jekyll-theme-minimal
